// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2_AP1_GreilynPolanco.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Concepto = "Many",
                            Fecha = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ProductoId = 2,
                            Concepto = "Pasas",
                            Fecha = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ProductoId = 3,
                            Concepto = "Ciruela",
                            Fecha = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ProductoId = 4,
                            Concepto = "Arandanos",
                            Fecha = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("ProductosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosDetalle");
                });

            modelBuilder.Entity("ProductosDetalle", b =>
                {
                    b.HasOne("Productos", null)
                        .WithMany("ProductosDetalle")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("Productos", b =>
                {
                    b.Navigation("ProductosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
